### ISSUE TITLE
Not able to see License Page in Swift 5

### ISSUE THREAD

**Issue by jobinsjohn** [vtourraine/AcknowList#108]
I am using Acknowlist to show the licenses of the SPM packages that I am using. The view gives a list of the packages that I am using like as shown below

<img width="300" alt="simulator_screenshot_A0FE8C2F-06E4-42C9-AF87-FC7B8C2C22C6" src="https://user-images.githubusercontent.com/3398498/222174552-ff39aabe-18c3-4e01-aeeb-d9180a5cc2bd.png">

But when I tap on one of the entries, I am taken to the default landing page of the repository rather than going into the license page as shown below.

For example if I tap on "acknowlist", then the following page is shown

<img width="300" alt="simulator_screenshot_87B5C198-0DC2-4E6E-B09C-BE58F62EF9F3" src="https://user-images.githubusercontent.com/3398498/222174962-ddf52543-a079-41bd-bba1-eee8541b729e.png">

Is this the expected behavior?

**Comment by vtourraine** [comment]
Hello @jobinsjohn  👋 

Yes, this is the expected behavior. SPM doesn’t specify licences, so AcknowList doesn’t know what to display and falls back to the repo URL (where one can usually find the licence).

If you really want to embed the licence for your SPM dependencies, you’ll have to specify them from your code, by customizing the `acknowledgements` property in your `AcknowListViewController`.

**Comment by vtourraine** [comment]
Hello @jobinsjohn,

Sorry to bring back this old issue, but it turns out that I found a solution for the problem you reported here. As you can see in #113, `AcknowList` will now try to fetch the missing libraries from the GitHub API. Not perfect, but a significant improvement in most cases. 

I haven’t released it as a new version yet. You can try it on the `main` branch. Let me know if you have any feedback.

**Comment by mischa-hildebrand** [comment]
*Note:* Only works with UIKit so far, not with SwiftUI.
