### ISSUE TITLE
1.1 violates semantic versioning

### ISSUE THREAD

**Issue by solidfox** [vtourraine/AcknowList#19]
Thanks for being so quick to upgrade to Swift 3.0! With the risk of sounding ungrateful semantic versioning (which CocoaPods uses) dictates no breaking changes in minor version increments so the way I see it 1.1 should really be 2.0 so people don't get attacked by compile errors when running pod update.

http://semver.org

**Comment by vtourraine** [comment]
Thanks for the feedback! I actually wondered about that. That's a tricky case, because the library interface itself is the same, it's "just" that you need a new compiler (a.k.a. Xcode 8). Maybe I made the wrong decision here, and I'm sorry if it's causing more confusion. 

Out of curiosity, have you seen this particular case being discussed somewhere else?

**Comment by solidfox** [comment]
Indeed your reasoning does make sense, I was also a bit unsure how this Swift 3.0 transition would happen at first but the big frameworks like Alamofire and RxSwift seem to be all bumping the major version. 

This makes sense since most people will have their pods configured as '~> 1.0' which should mean "anything compatible with the 1.0 syntax". This makes for a controlled transition where users of the frameworks can choose when to go Swift 3.0 and bump the versions of all their dependencies at that time.

**Comment by vtourraine** [comment]
Agreed. Well, I'll try to remember that next year for Swift 4. The more you know... 💡
