### ISSUE TITLE
version 1.1 is still asked by Xcode to convert to swift 3

### ISSUE THREAD

**Issue by liyukuang** [vtourraine/AcknowList#21]

**Comment by vtourraine** [comment]
Thanks for the feedback. I think the Swift 3 conversion info is stored at the `.xcodeproj` level, but I’m not sure.

What method are you using to import AcknowList into your project (drag n drop files, CocoaPods, etc)?

**Comment by liyukuang** [comment]
Thanks for your repo! I was using CocaPods for installing, and then I opened the workspace and Xcode detected AcknowList was written with earlier version of swift and asked me to convert it to Swift 3. I saw in other repo (the Eureka) that people mentioned you need to add Swift version 3.0 somewhere?

**Comment by vtourraine** [comment]
That's interesting. So CocoaPods apparently started using a `.swift-version` file to specify the Swift version, and the latest AcknowList (v1.1) does include that file. But currently, I think you need a beta version of CocoaPods (v1.1.0.rc.x) to apply this bit of configuration. 

So hopefully it's in the process of being fixed by default, but for now it requires a bit of extra work. Please let me know if the problem persists.

**Comment by OliverZiegler** [comment]
But Xcode also shows code changes after selecting "Convert to Swift 3 Syntax".

As I can see its only the change from `public` to `open`.

Good explanation for the differences: http://stackoverflow.com/a/38950955/2408916

So why would you prevent people from subclassing AcknowListViewController?

**Comment by vtourraine** [comment]
You’re totally right, that’s an important distinction. And that should totally be `open`, because I agree the class should be subclassable. Do you want to send a quick pull request?

**Comment by OliverZiegler** [comment]
Here you are ;)

**Comment by vtourraine** [comment]
Fixed with #22
