### ISSUE TITLE
Ability to distinguish between development pods

### ISSUE THREAD

**Issue by irace** [vtourraine/AcknowList#28]
Unsure if this is possible or not, but it’d be great if `Acknow` had a `let isDevelopmentPod: Bool` property on it, to allow development pods to be more easily filtered out.

**Comment by vtourraine** [comment]
That’s a very interesting idea, I can definitely see that being useful.

I’m assuming the choice between ”dev” and “prod” would have to be explicit, because I don’t know any standard way to detect that from the library itself. 

So how would you like to specify that? Offer an initializer with 2 arrays of `Acknow`, and a `Bool`/`enum` to switch between the two?

**Comment by irace** [comment]
Interesting – yeah, I see what you mean. The `Pods-acknowledgements.plist` file doesn’t give any way to disambiguate.

I wonder if this is really an issue that should be opened on the CocoaPods repository itself, asking for some kind of “development pod or not” metadata flag to be added to that repository. 

Basically, I use development pods to organize private, first-party code, but don’t really want that leaking into the acknowledgements. Right now I’ve subclassed `AcknowListViewController` and just manually filtered them out, just need to remember to update the list of names whenever I refactor my internal dependencies.

**Comment by vtourraine** [comment]
Exactly. And just to be clear, you don’t need to subclass `AcknowListViewController` to filter the acknowledgements array.

I would be interested to hear other people’s takes on that problem. I would bet that’s a fairly common use case. I’m afraid the solutions are very app-specific though.
