### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by mkismy** [vtourraine/AcknowList#38]
From AcknowList 1.3, there is a compile issue on Xcode 9 with swift 3.2. It works fine on 1.2.

```
(directory)/Pods/AcknowList/Source/AcknowListViewController.swift:344:163: Type 'NSAttributedStringKey' (aka 'NSString') has no member 'font'
```

**Comment by vtourraine** [comment]
Thanks for the feedback.

AcknowList 1.3 (and up) is only compatible with Swift 4, as mentioned in the `README` and the `.swift-version` file.

AcknowList 1.2.x supports Swift 3.

If you need explicit support for Swift 3.2, you can send a pull request that we could tag 1.2.9, for instance. But since Xcode 9 also support Swift 4, there might be a simpler solution, depending on how exactly you use this code in your project.
