### ISSUE TITLE
Please update for Swift 5

### ISSUE THREAD

**Issue by OkiRules** [vtourraine/AcknowList#49]
Please update for Swift 5 support

Thanks!

**Comment by vtourraine** [comment]
Hello Oscar, and thank you for reaching out. Unfortunately I don’t have the latest Xcode version installed yet, so I can’t test this library with Swift 5.

If you do, feel free to open the workspace, migrate the code to Swift 5 (there’s probably very little change beyond the project settings), and send me a pull request. 🚀

**Comment by OkiRules** [comment]
Hi Vincent,

I have created a pull request for this update.

Thanks!

**Comment by vtourraine** [comment]
Implemented with #50

**Comment by vtourraine** [comment]
@larsschwegmann I’ve tried to push the update earlier this week, but apparently Swift 5 isn’t supported by CocoaPods yet. Unless I’m missing something?

**Comment by larsschwegmann** [comment]
@vtourraine Hmm, I've actually never submitted/updated a pod to the cocoapods trunk myself, but other pods that I use already upgraded to Swift 5 and successfully submitted their updated version. Take [Moya](https://cocoapods.org/pods/Moya) for example (v. 13.0.0) which uses Swift 5 and depends on Xcode 10.2

What happens exactly when you try to submit it using `pod trunk push`? ´Do you get an Error message? I would really like to get rid of these annoying warnings in Xcode 😄

**Comment by vtourraine** [comment]
That’s interesting. So they must have used a new beta, or something like that. I’ll look into this as soon as I can, but in the meantime, you should be able to update your Podfile to request a specific commit, thus getting the Swift 5 version from `master`.

**Comment by vtourraine** [comment]
My bad, I misunderstood the error I was getting when trying to push to trunk. The `pod` tool uses `xcodebuild` (a.k.a. Xcode) to check the podspec file before pushing it, and like I mentioned, I don’t have the latest Xcode version with Swift 5 installed on my machine. So that's a bummer. 😞 

I’m sure I’ll manage to update my machine to Mojave and Xcode 10.2 eventually, but in the meantime, I’m open to suggestions, and hopefully the trick of pointing to `master` from your Podfile (as mentioned previously) should help you avoid the issue.

**Comment by OkiRules** [comment]
Why don’t you update your computer and Xcode? Mojave is much better than High Sierra?

**Comment by vtourraine** [comment]
@OkiRules That’s down to professional constraints, basically out of my control.

**Comment by vtourraine** [comment]
@OkiRules Good news: the Swift 5 version is finally available from CocoaPods (v1.9) 🎉 

Sorry it took so long.
